&init

! [最大値]
melem  = 900000 ! 要素数
mpoint =  150000 ! 節点数
mmate  = 10      ! 材質数
mtface = 1000    ! 熱伝達境界面数
mtfce  = 1000    ! 熱伝達境界面上の三角形数
mbandt = 10      ! バンド幅(節点数に対する倍率)
mbound = 55000   ! 境界ブロック数
mblock = 300     ! 材質ブロック数
mtdble = 10000   ! 二重節点
mtdbl  = 10000   ! 〃
mtnod  = 10      ! 結果節点数
mpc    = 100     ! 周期境界節点
mwave  = 1       ! 波形数
!mwvpnt = 100     ! 波形上節点数

!melem2d  = 3000000 ! 二次元要素数
!mpoint2d = 200000  ! 二次元節点数
!mofset   = 0	    ! オフセット値
/
